branch-defaults:
  default:
    environment: Udagramapirken-env-1
    group_suffix: null
  deploy:
    artifact: www/Archive.zip
  main:
    environment: Udagramapirken-env-1
global:
  application_name: Udagramapirken
  branch: null
  default_ec2_keyname: udagram-api-kp
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
