branch-defaults:
  default:
    environment: Udagramapirkenenv-env-1
global:
  application_name: Udagramapirkenenv
  branch: null
  default_ec2_keyname: udagram-api-kp
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
deploy:
  artifact: www/Archive.zip  
