version: 2.1
orbs: # import reusable packages of configuration in the namespace
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-cli: circleci/aws-cli@2.0.2
jobs: #collection of steps to be executed in signle unit
  build:
    branches:
      only:
        - main
    docker:
      - image: "cimg/base:stable"
    steps: # set the collection of executable
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run: 
          name: Back-End Install
          command: npm run backend:install
      - run:
          name: Back-End Build
          command: npm run backend:build
      - run:
          name: Deploy Back-End
          command: npm run backend:deploy
      - run:
          name: Front-End Install
          command: npm run frontend:install
      - run:
          name: Front-End Build
          command: npm run frontend:build
      - run:
          name: Deploy Front-End
          command: npm run frontend:deploy  
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master          


 